# Generated by Django 5.2 on 2025-04-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
